[package]
name = "LeDron_James"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git"}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
crossbeam-channel = "0.5.13"
rand = "0.9.0-beta.0"